version: "3.4"

services:
  web:
    image: node:10-alpine
    command: /app/bin/serve.sh
    restart: always
    volumes:
      # share cache so the web app can clear it
      - cache:/cache

  # static files, ssl, and caching
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${PORT:-8445}:80
    restart: always
    volumes:
      - $CONF:/etc/nginx/conf.d/default.conf:ro
      - logs:/logs
      - cache:/cache
      # share files from web
      - ./public:/static:ro

volumes:
  logs:
  cache: