version: "3.7"

services:
  # NodeJS React server-side and static files
  web:
    build: .
    volumes:
      - public:/static
    restart: on-failure:3

  # static files, and caching
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${PORT:-8445}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # share files from web
      - public:/static:ro
    restart: on-failure:3

volumes:
  public:
