version: "3.4"

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      # share cache so the web app can clear it
      - cache:/cache

  # static files, ssl, and caching
  nginx:
    image: nginx
    ports:
      - ${PORT:-8005}:80
      - ${SSLPORT:-8445}:443
    restart: always
    volumes:
      - $CONF:/etc/nginx/conf.d/default.conf:ro
      - $CERTS_DIR:/etc/nginx/certs:ro
      - ./nginx/ssl-cert:/etc/nginx/ssl-cert:ro
      - logs:/logs
      - cache:/cache
      # share files from web
      - ./public:/static:ro

volumes:
  logs:
  cache: