version: "3.7"

services:
  # NodeJS React server-side and static files
  web:
    build: .
    volumes:
      # share cache from nginx container
      - cache:/cache
      - public:/static
    restart: on-failure:3

  # static files, ssl, and caching
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${PORT:-8445}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/logs
      - cache:/cache
      # share files from web
      - public:/static:ro
    restart: on-failure:3

volumes:
  logs:
  cache:
  public:
