version: "3.7"

services:
  # NodeJS React server-side and static files
  web:
    build: .
    image: registry.gitlab.com/bozdoz/bozdoz-com:${TAG:-latest}
    env_file: .env
    volumes:
      # share cache from nginx container
      - cache:/cache
      - public:/static
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # static files, ssl, and caching
  nginx:
    image: nginx:stable-alpine
    env_file: .env
    ports:
      - ${PORT:-8445}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - cache:/cache
      # share files from web
      - public:/static:ro
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  cache:
  public:
