version: "3.7"

services:
  web:
    build: .
    image: registry.gitlab.com/bozdoz/bozdoz-com:${TAG:-latest}
    volumes:
      # share cache so this service can clear it
      - cache:/cache
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

  # static files, ssl, and caching
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${PORT:-8445}:80
    volumes:
      - $CONF:/etc/nginx/conf.d/default.conf:ro
      - logs:/logs
      - cache:/cache
      # share files from web
      - ./public:/static:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

volumes:
  logs:
  cache: